### ISSUE TITLE
Cannot transform sap.ui.define when no function is provided

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [ui5-community/babel-plugin-transform-modules-ui5#50]
Hello,

I noticed that the babel-plugin-transform-modules-ui5 cannot transform such definition which is valid from a UI5 perspective (even if a sap.ui.require could be an alternative !)

```
sap.ui.define("", [
    "foo/bar/MyResource"
]); 
```

Error:
```
TypeError: C:\project\test\unit\AllTests.ts: Cannot read property 'params' of undefined
    at getRequiredParamsOfSAPUIDefine (C:\project\node_modules\babel-plugin-transform-modules-ui5\dist\classes\visitor.js:154:23)
    at PluginPass.CallExpression (C:\project\node_modules\babel-plugin-transform-modules-ui5\dist\classes\visitor.js:111:32)
    at NodePath._call (C:\project\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\project\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\project\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (C:\project\node_modules\@babel\traverse\lib\context.js:110:16)
    at TraversalContext.visitSingle (C:\project\node_modules\@babel\traverse\lib\context.js:79:19)
    at TraversalContext.visit (C:\project\node_modules\@babel\traverse\lib\context.js:138:19)
    at Function.traverse.node (C:\project\node_modules\@babel\traverse\lib\index.js:76:17)
    at NodePath.visit (C:\project\node_modules\@babel\traverse\lib\path\context.js:97:18) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

You can find a workardound by defining it that way:
```
sap.ui.define("", [
      "foo/bar/MyResource"
], () => {
    // Empty
});
```

Issue is located in babel-plugin-transform-modules-ui5\dist\classes\visitor.js

And I made a local fix by checking checking callbackNode against undefined.
```
function getRequiredParamsOfSAPUIDefine(path, node) {
  const defineArgs = node.arguments;
  const callbackNode = defineArgs.find(argNode => _core.types.isFunction(argNode));
  **HERE** 
  return callbackNode.params; // Identifier
}
```

But I don't know how the plugin itself works and if this is viable.
Do you think a fix could be provided. Using sap.ui.define with no content helps when for example you are running OPA tests with karma. They can be loaded, but you do not need to define a function. Maybe there are other use cases.

Thanks

**Comment by JasonMaritz** [comment]
Also have this issue. The workaround is fine for now but is still an ongoing issue
